/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_dc18f5b2 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/bzmzjtevjnvngjslwczo/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
// import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

// const client = () => createClient(
//   Deno.env.get("SUPABASE_URL"),
//   Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),
// );

// // Set stores a key-value pair in the database.
// export const set = async (key: string, value: any): Promise<void> => {
//   const supabase = client()
//   const { error } = await supabase.from("kv_store_dc18f5b2").upsert({
//     key,
//     value
//   });
//   if (error) {
//     throw new Error(error.message);
//   }
// };

// // Get retrieves a key-value pair from the database.
// export const get = async (key: string): Promise<any> => {
//   const supabase = client()
//   const { data, error } = await supabase.from("kv_store_dc18f5b2").select("value").eq("key", key).maybeSingle();
//   if (error) {
//     throw new Error(error.message);
//   }
//   return data?.value;
// };

// // Delete deletes a key-value pair from the database.
// export const del = async (key: string): Promise<void> => {
//   const supabase = client()
//   const { error } = await supabase.from("kv_store_dc18f5b2").delete().eq("key", key);
//   if (error) {
//     throw new Error(error.message);
//   }
// };

// // Sets multiple key-value pairs in the database.
// export const mset = async (keys: string[], values: any[]): Promise<void> => {
//   const supabase = client()
//   const { error } = await supabase.from("kv_store_dc18f5b2").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
//   if (error) {
//     throw new Error(error.message);
//   }
// };

// // Gets multiple key-value pairs from the database.
// export const mget = async (keys: string[]): Promise<any[]> => {
//   const supabase = client()
//   const { data, error } = await supabase.from("kv_store_dc18f5b2").select("value").in("key", keys);
//   if (error) {
//     throw new Error(error.message);
//   }
//   return data?.map((d) => d.value) ?? [];
// };

// // Deletes multiple key-value pairs from the database.
// export const mdel = async (keys: string[]): Promise<void> => {
//   const supabase = client()
//   const { error } = await supabase.from("kv_store_dc18f5b2").delete().in("key", keys);
//   if (error) {
//     throw new Error(error.message);
//   }
// };

// // Search for key-value pairs by prefix.
// export const getByPrefix = async (prefix: string): Promise<any[]> => {
//   const supabase = client()
//   const { data, error } = await supabase.from("kv_store_dc18f5b2").select("key, value").like("key", prefix + "%");
//   if (error) {
//     throw new Error(error.message);
//   }
//   return data?.map((d) => d.value) ?? [];
// };


import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.8";

const client = () =>
  createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""
  );

// ─────────────────────────────────────────────────────────────────────────────
// SET
// ─────────────────────────────────────────────────────────────────────────────

export const set = async (
  key: string,
  value: any
): Promise<void> => {
  const supabase = client();

  const { error } = await supabase
    .from("kv_store_dc18f5b2")
    .upsert({
      key,
      value,
    });

  if (error) {
    throw new Error(error.message);
  }
};

// ─────────────────────────────────────────────────────────────────────────────
// GET
// ─────────────────────────────────────────────────────────────────────────────

export const get = async (
  key: string
): Promise<any> => {
  const supabase = client();

  const { data, error } = await supabase
    .from("kv_store_dc18f5b2")
    .select("value")
    .eq("key", key)
    .maybeSingle();

  if (error) {
    throw new Error(error.message);
  }

  return data?.value;
};

// ─────────────────────────────────────────────────────────────────────────────
// DELETE ONE
// ─────────────────────────────────────────────────────────────────────────────

export const del = async (
  key: string
): Promise<void> => {
  const supabase = client();

  const { error } = await supabase
    .from("kv_store_dc18f5b2")
    .delete()
    .eq("key", key);

  if (error) {
    throw new Error(error.message);
  }
};

// ─────────────────────────────────────────────────────────────────────────────
// MULTI SET
// ─────────────────────────────────────────────────────────────────────────────

export const mset = async (
  keys: string[],
  values: any[]
): Promise<void> => {
  if (keys.length !== values.length) {
    throw new Error(
      "Keys and values must have the same length."
    );
  }

  if (keys.length === 0) {
    return;
  }

  const supabase = client();

  const rows = keys.map((key, index) => ({
    key,
    value: values[index],
  }));

  const { error } = await supabase
    .from("kv_store_dc18f5b2")
    .upsert(rows);

  if (error) {
    throw new Error(error.message);
  }
};

// ─────────────────────────────────────────────────────────────────────────────
// MULTI GET
// ─────────────────────────────────────────────────────────────────────────────

export const mget = async (
  keys: string[]
): Promise<any[]> => {
  if (keys.length === 0) {
    return [];
  }

  const supabase = client();

  const { data, error } = await supabase
    .from("kv_store_dc18f5b2")
    .select("key, value")
    .in("key", keys);

  if (error) {
    throw new Error(error.message);
  }

  return data?.map((row) => row.value) ?? [];
};

// ─────────────────────────────────────────────────────────────────────────────
// MULTI DELETE
// ─────────────────────────────────────────────────────────────────────────────

export const mdel = async (
  keys: string[]
): Promise<void> => {
  if (keys.length === 0) {
    return;
  }

  const supabase = client();

  const { error } = await supabase
    .from("kv_store_dc18f5b2")
    .delete()
    .in("key", keys);

  if (error) {
    throw new Error(error.message);
  }
};

// ─────────────────────────────────────────────────────────────────────────────
// GET BY PREFIX
// ─────────────────────────────────────────────────────────────────────────────

export const getByPrefix = async (
  prefix: string
): Promise<any[]> => {
  const supabase = client();

  const { data, error } = await supabase
    .from("kv_store_dc18f5b2")
    .select("key, value")
    .like("key", `${prefix}%`);

  if (error) {
    throw new Error(error.message);
  }

  return data?.map((row) => row.value) ?? [];
};

// ─────────────────────────────────────────────────────────────────────────────
// GET ENTRIES BY PREFIX
// ─────────────────────────────────────────────────────────────────────────────

export const getEntriesByPrefix = async (
  prefix: string
): Promise<
  {
    key: string;
    value: any;
  }[]
> => {
  const supabase = client();

  const { data, error } = await supabase
    .from("kv_store_dc18f5b2")
    .select("key, value")
    .like("key", `${prefix}%`);

  if (error) {
    throw new Error(error.message);
  }

  return data ?? [];
};

// ─────────────────────────────────────────────────────────────────────────────
// DELETE BY PREFIX
// ─────────────────────────────────────────────────────────────────────────────

export const deleteByPrefix = async (
  prefix: string
): Promise<number> => {
  const supabase = client();

  const { data, error } = await supabase
    .from("kv_store_dc18f5b2")
    .select("key")
    .like("key", `${prefix}%`);

  if (error) {
    throw new Error(error.message);
  }

  const keys = data?.map((row) => row.key) ?? [];

  if (keys.length === 0) {
    return 0;
  }

  const { error: deleteError } = await supabase
    .from("kv_store_dc18f5b2")
    .delete()
    .in("key", keys);

  if (deleteError) {
    throw new Error(deleteError.message);
  }

  return keys.length;
};