/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "yhguvzytdvzdbvmkzczp"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InloZ3V2enl0ZHZ6ZGJ2bWt6Y3pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk3ODA0NjcsImV4cCI6MjA5NTM1NjQ2N30.G3K8wilOhX36v5af_oT-dPAkjkz5J7Q8V2PevDY6_DM"
